### ISSUE TITLE
Transaction list: sorting bug

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#225]
0.4.39-BETA

http://s21.postimg.org/gydbm4jfb/transaction_list_not_sorted.png

"Recent Transactions" (Dashboard) is also not always sorting correct.

Edit:
I just understood that it is sorting the confirmation row. I think you should sort the timestamp row...

**Comment by BloodyRookie** [comment]
I don't think it is a good idea to sort by timestamp. The timestamp of a transaction doesn't say anything about the time it was included in a block. So if a transaction is in the cache for hours and then eventually gets included, it is instantly burried by newer transactions that got served first (because of higher fees).

**Comment by fyahfox** [comment]
Hm, you are right. Well ok, we need a manual sort feature for every row. But that is probably a lot of work and it isn't high priority.

**Comment by Jaguar0625** [comment]
Closing as won't fix.
