### ISSUE TITLE
Tooltip for "multisig transaction" symbol

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#243]
0.5.4-BETA

... is now "Incoming transaction".
... should be "Incoming multisig transaction".

**Comment by BloodyRookie** [comment]
Not sure if that is necessary. Multisig transactions have a different icon on the left side.

**Comment by gimer** [comment]
On recipients side:
![image](https://cloud.githubusercontent.com/assets/6421169/6096814/5ba383a6-afa5-11e4-8ced-f1ef811bb8b2.png)

On issuer side:
![image](https://cloud.githubusercontent.com/assets/6421169/6096816/730bd2f0-afa5-11e4-9b7e-a92a3dbd45fc.png)

On actual multisig account (it's where funds come from, that's why it's red):
![image](https://cloud.githubusercontent.com/assets/6421169/6096823/9a7e9b2e-afa5-11e4-8fcd-89b4785dce96.png)

**Comment by Jaguar0625** [comment]
Hopefully fixed in 0.5.11

**Comment by fyahfox** [comment]
Not yet fixed in 0.5.12-BETA

To be clear: I was just talking about the tooltip. (And I know, this is a minor minor issue ;) I just thought it would be more consistent.)

http://s3.postimg.org/oebvrmfub/NEM_tooltip_multisig.png

**Comment by gimer** [comment]
The thing is, it IS incoming transaction, to be more precise incoming multisig transaction, but we can't put all possiblities in tooltip.

**Comment by fyahfox** [comment]
okay :)
