### ISSUE TITLE
Tried to make a multisig account but the default fee was 0

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#329]
0.5.18

I think the default fee for multisig should be higher than 0.  I tried to make an account into a multisig account but I got the 306 error.  I'm pretty sure because I tried to push through the transaction with no fee.  I then tried to send with a fee of 50 XEM and it worked no problem.  

https://www.dropbox.com/s/t4x3gx5zzuuki7p/multisig%200%20fee%20error%20306.png?dl=0

**Comment by gimer** [comment]
so did the fee was set to 0, when selecting "use minimum"? if so, that's a bug

**Comment by jabo38** [comment]
yes, exactly

**Comment by gimer** [comment]
Cannot reproduce, maybe it's been fixed already, when trying to set multsig to zero, I cannot even send transaction:

![image](https://cloud.githubusercontent.com/assets/6421169/6771042/5bfa1294-d0d3-11e4-9c0b-ab1e2b3f90bd.png)

when checking "use minimum", proper amount is choosen
![image](https://cloud.githubusercontent.com/assets/6421169/6771059/d1313e16-d0d3-11e4-907b-1cf77323e793.png)

(there's probability, it was incorrectly calculated in 5.18 and 5.19, due to transaction fees)
